#! /bin/bash

# Tool to install https://github.com/projectdiscovery/httpx#installation-instructions

error () {
    echo "Error: $1"
    echo ""
    echo "Usage:"
    echo "./dirfuzz domains.txt wordlist.txt"
    echo "./dirfuzz "http://xyz.io" wordlist.txt"
    exit 1
}

# Main start
if [[ -f $1 ]]
then
    # If file
    if [[ -f $2 ]]
    then
        cat $1 | httpx -path $2 -fc 400,403,404
    else
        error "File wordlist not specified"
    fi
elif [[ ! -z $1 ]]
then
    # If string
    if [[ -f $2 ]]
    then
        httpx -path $2 -fc 400,403,404 $1
    else
        error "File wordlist not specified"
    fi
else
    error "File or string for domains not specified"
fi